services:
  app:
    container_name: qrmenu-app
    build:
      context: .
      dockerfile: Dockerfile
    image: qrmenu
    ports:
      - "9090:80"
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - qrmenu-network
    environment:
      - LC_ALL=tr_TR.UTF-8
      - LANG=tr_TR.UTF-8

  db:
    image: mysql:8.0
    container_name: underground-db
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: underground-db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: root
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    networks:
      - qrmenu-network

networks:
  qrmenu-network:

volumes:
  mysql-data:
